In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
# reshape
# To reshape a NumPy array, you primarily use the reshape() method or function,
# which changes the array's dimensions without altering its data

In [3]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

In [4]:
new_arr_2d = arr.reshape(4, 3) # or arr.reshape((4, 3))
print(f"\nReshaped to 4x3:\n{new_arr_2d}")
print(f"New shape: {new_arr_2d.shape}")



Reshaped to 4x3:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
New shape: (4, 3)


In [5]:
new_arr_3d = arr.reshape(2, 3, 2)
print(f"\nReshaped to 3D:\n{new_arr_3d}")
print(f"New shape: {new_arr_3d.shape}")



Reshaped to 3D:
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
New shape: (2, 3, 2)


### np array function 

In [6]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[87., 24., 94.],
       [90., 30., 20.],
       [67., 49., 28.]])

In [7]:
 # max/min/sum/prod
# As their names suggest max find out the maximum value and same goes for miniumum!
# Sum of all values in the matrix and same goes for the prod

In [8]:
# np.max(a1,axis=1)
# 0 -> colums and 1 -> rows

np.prod(a1,axis=1)
# it means all the value in x axis will be mutliplied [80. * 89 * 54.] = 384480
# 13 * 9 * 26  = 3042
# 96 * 9 * 37 = 31968


array([196272.,  54000.,  91924.])

In [9]:
np.prod(a1,axis=0)

array([524610.,  35280.,  52640.])

In [10]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)
# Matrix dot product A(n,m) * B(m,n) = the column of A (m) =  the row of B(m) then the product will be (n,n)
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [11]:
# round,floor, ceil 
# Round => round off to nearst integers!
a = np.random.random((2,3))*100
a

array([[38.07204441, 82.75999911, 83.72137362],
       [89.70598843, 89.09550852,  3.13662909]])

In [12]:
np.round(a)

array([[38., 83., 84.],
       [90., 89.,  3.]])

In [13]:
# Floor always rounds a number DOWN to the nearest integer
np.floor(a)

array([[38., 82., 83.],
       [89., 89.,  3.]])

# Indexing and Slicing

# Two type of indexing one goes from L to R which is +ve indexing and another goes from R to L => -ve indexing

In [14]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [15]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
# For accessing any element in 2D array just the [the rows and column number ] where the number is located
a2[2,3]

np.int64(11)

In [17]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [18]:
# Accessing value in 3D array / tensor we have too give three values [as we know the 3d is made up of 2d's]
# so here a3 is made up of two 2d arrays![[0, 1], [2, 3]] ,[[4, 5], [6, 7]]] so two 2d array ans their index 0,1
# 1. we have to index of 2d array
# 2. then just treat it same way as 2d array [the row number and column number ]
a3[0,1,0]

np.int64(2)

In [19]:
a3[1,1,0]

np.int64(6)

# Slicing

In [20]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
a1[2:8]

array([2, 3, 4, 5, 6, 7])

In [22]:
# Slicing in 2d[rows, columns] :=>means till end 
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [24]:
a2[1,::3]

array([4, 7])

In [25]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [26]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [27]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [28]:
a2[:,0]

array([0, 4, 8])

In [29]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [30]:
a3[0,1]

array([3, 4, 5])

In [31]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [32]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [33]:
a3[1,:,1]

array([10, 13, 16])

In [34]:
a3[1,::2,::2]

array([[ 9, 11],
       [15, 17]])

In [35]:
a3[::2,::2,::2]

array([[[ 0,  2],
        [ 6,  8]],

       [[18, 20],
        [24, 26]]])

**Reshaping**

In [36]:
# ravel, reshape, transpose 
# reshape already studied 
# ravel convert n dimension array to 1d array
# transpose is as same as that of matrix transpose 

In [37]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [39]:
# Ravel
np.ravel(a2)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# Advance Numpy

Numpy is faster than the list of python [it uses static array {fixed size} ] because it doesnot use referntial array 
means numpy direclty store the the item/value in memmory ! not its address

In [40]:
# Speed
# List
a = [i for i in range(10000000)]
b = [i for i in range(10000000,20000000)]

c = []
import time 

start = time.time()
for i in range(len(a)):
  c.append(a[i] + b[i])
print(time.time()-start)

1.8864374160766602


In [41]:
# Numpy
import numpy as np
# it will create array of values from  1 to 1 cr
a = np.arange(10000000) 
b = np.arange(10000000,20000000)

start = time.time()
c = a + b
print(time.time()-start)

0.17865633964538574


In [42]:
2.21/0.19
# time taken by list of python/ time taken by numpy

11.631578947368421

### Advance Indexing

In [43]:
# Fancy indexing is nothing just pass one more list 
# Example a[[]]

In [44]:
a = np.arange(24).reshape(6,4)

In [45]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [46]:
a[[2,3],::2]

array([[ 8, 10],
       [12, 14]])

In [47]:
a[:,[0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

# Boolean Indexing

In [48]:
# Filtering data based on some conditon we can use boolean indexing 
a = np.random.randint(1,100,24).reshape(6,4)
a

array([[57, 39, 51, 31],
       [35, 33, 69, 15],
       [40, 82, 97, 19],
       [20,  7, 79,  5],
       [97, 28, 50, 13],
       [ 3, 65, 44,  5]])

In [49]:
# Filtering in arrays : number which are greater than 50 in array
a>50

array([[ True, False,  True, False],
       [False, False,  True, False],
       [False,  True,  True, False],
       [False, False,  True, False],
       [ True, False, False, False],
       [False,  True, False, False]])

In [50]:
# Look we get only true values //true means number which satisfy the condition : number greater than 50
a[a>50]

array([57, 51, 69, 82, 97, 79, 97, 65])

In [51]:
# find all number greater than 50 and  are even
# & bitwise operator 
a[(a>50) & (a%2==0)]

array([82])

# Broadcasting

The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations.
The smaller array is “broadcast” across the larger array so that they have compatible shapes.

Broadcasting is done by the numpy itself ! we just know will broadcasting happen or not ? that's it !
To perform broadcasting you have to follow a set of 3 rules, <br/>
Rule 1: <br/>
**Make the two arrays have the same number of dimensions.**
If the numbers of dimensions of the two arrays are different, add new dimensions with size 1 to the head of the array with the smaller dimension.

Rule 2 : <br/>
**Make each dimension of the two arrays the same size.**

If the sizes of each dimension of the two arrays do not match, dimensions with size 1 are stretched to the size of the other array.<br/>
Rule 3:<br />
**If there is a dimension whose size is not 1 in either of the two arrays, it cannot be broadcasted, and an error is raised.**

In [52]:
a = np.arange(12).reshape(4,3)
b = np.arange(3)

print(a)
print(b)

print(a+b)
# This will give result because broadcasting will happen here!
# b array will be converted into 2D as it is in 1D by adding 1 in head (1,3) : now this one will be
# stretched to 4[corresponding to array a.] array A (4,3) =  Array B(4,3)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [53]:
a = np.arange(3).reshape(1,3)
b = np.arange(4).reshape(4,1)

print(a)
print(b)

print(a + b)
# Same this will also perform broadcasting

[[0 1 2]]
[[0]
 [1]
 [2]
 [3]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


In [54]:
a = np.arange(12).reshape(3,4)
b = np.arange(12).reshape(4,3)

print(a)
print(b)


# There will be no bradcasting as per 3rd rules. print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


# Working with Missing values 

In [55]:
# Working with missing values -> np.nan
a = np.array([1,2,3,4,np.nan,6])
a

array([ 1.,  2.,  3.,  4., nan,  6.])

In [56]:
# Applying boolean indexing  : ~ is not operator
a[~np.isnan(a)]

array([1., 2., 3., 4., 6.])